DROP TABLE TRAVNJAK CASCADE CONSTRAINTS;
DROP TABLE DRVORED CASCADE CONSTRAINTS;
DROP TABLE PARK CASCADE CONSTRAINTS;
DROP TABLE RADNIK CASCADE CONSTRAINTS;
DROP TABLE DRVO CASCADE CONSTRAINTS;
DROP TABLE SPOMENIK CASCADE CONSTRAINTS;
DROP TABLE SKULPTURA CASCADE CONSTRAINTS;
DROP TABLE KLUPA CASCADE CONSTRAINTS;
DROP TABLE FONTANA CASCADE CONSTRAINTS;
DROP TABLE SVETILJKA CASCADE CONSTRAINTS;
DROP TABLE IGRALISTE CASCADE CONSTRAINTS;
DROP TABLE ZASTICENI_OBJ CASCADE CONSTRAINTS;
DROP SEQUENCE ZELENA_POVRSINA_PK_SEQUENCE;
DROP SEQUENCE OBJEKAT_PK_SEQUENCE;
DROP SEQUENCE ZASTICENI_OBJ_PK_SEQUENCE;
DROP SEQUENCE RADNIK_PK_SEQUENCE;

CREATE SEQUENCE ZELENA_POVRSINA_PK_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE OBJEKAT_PK_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ZASTICENI_OBJ_PK_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RADNIK_PK_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE TRAVNJAK
(
    BROJ NUMBER PRIMARY KEY,
    OPSTINA VARCHAR2(15),
    UGROZENOST VARCHAR2(15),
    ADRESA_ZGRADE VARCHAR2(60),
    POVRSINA_A NUMBER
);
CREATE TABLE DRVORED
(
    BROJ NUMBER PRIMARY KEY,
    OPSTINA VARCHAR2(15),
    UGROZENOST VARCHAR2(15),
    ULICA VARCHAR2(60),
    BR_STABALA NUMBER,
    VRSTA_DRVETA VARCHAR2(15)
);
CREATE TABLE PARK
(
    BROJ NUMBER PRIMARY KEY,
    OPSTINA VARCHAR2(30),
    UGROZENOST VARCHAR2(15),
    NAZIV VARCHAR(30),
    POVRSINA_HA NUMBER,
    ID_SEFA NUMBER
);
CREATE TABLE RADNIK
(
    MBR NUMBER UNIQUE,
    LIME VARCHAR2(15),
    SIME VARCHAR2(15),
    PREZIME VARCHAR2(15),
    BR_RAD_KNJIZICE NUMBER PRIMARY KEY,
    ADRESA VARCHAR2(60),
    DAT_RODJENJA DATE,
    STRUCNA_SPREMA VARCHAR2(15),
    ODRZAVA_ZELENILA NUMBER(1),
    ODRZAVA_HIGIJENU NUMBER(1),
    ODRZAVA_OBJ_PARKA NUMBER(1),
    BR_PARKA NUMBER,
    CONSTRAINT RADNIK_CHK CHECK 
    (
        ODRZAVA_ZELENILA IN (1, 0) AND
        ODRZAVA_HIGIJENU IN (1, 0) AND
        ODRZAVA_OBJ_PARKA IN (1, 0)
    )
);
CREATE TABLE DRVO
(
    BR_OBJ NUMBER PRIMARY KEY,
    VRSTA VARCHAR2(15),
    VISINA_KROSNJE NUMBER,
    POVRSINA_KROSNJE NUMBER,
    OBIM_DEBLA NUMBER,
    DAT_SADJENJA DATE,
    BR_PARKA NUMBER NOT NULL,
    ZASTICENI_OBJ_ID NUMBER
);
CREATE TABLE SPOMENIK
(
    BR_OBJ NUMBER PRIMARY KEY,
    BR_PARKA NUMBER NOT NULL,
    ZASTICENI_OBJ_ID NUMBER
);
CREATE TABLE SKULPTURA
(
    BR_OBJ NUMBER PRIMARY KEY,
    BR_PARKA NUMBER NOT NULL,
    ZASTICENI_OBJ_ID NUMBER
);
CREATE TABLE KLUPA
(
    BR_OBJ NUMBER PRIMARY KEY,
    BR_PARKA NUMBER NOT NULL
);
CREATE TABLE FONTANA
(
    BR_OBJ NUMBER PRIMARY KEY,
    BR_PARKA NUMBER NOT NULL
);
CREATE TABLE SVETILJKA
(
    BR_OBJ NUMBER PRIMARY KEY,
    BR_PARKA NUMBER NOT NULL
);
CREATE TABLE IGRALISTE
(
    BR_OBJ NUMBER PRIMARY KEY,
    BR_IGRACAKA NUMBER,
    GODINE_OD NUMBER CHECK (GODINE_OD >= 0) NOT NULL,
    GODINE_DO NUMBER,
    PESAK CHAR(2) CHECK (PESAK IN ('Da', 'Ne')),
    BR_PARKA NUMBER NOT NULL
);
CREATE TABLE ZASTICENI_OBJ
(
    ZASTICENI_OBJ_ID NUMBER PRIMARY KEY,
    OPIS VARCHAR2(200),
    INSTITUCIJA VARCHAR2(60),
    DAT_STAVLJANJA_POD_ZASTITU DATE,
    GOD_TROSKOVI NUMBER
);

ALTER TABLE PARK ADD CONSTRAINT PARK_RADNIK_FK FOREIGN KEY (ID_SEFA)
REFERENCES RADNIK (BR_RAD_KNJIZICE) ENABLE;

ALTER TABLE RADNIK ADD CONSTRAINT RADNIK_PARK_FK FOREIGN KEY (BR_PARKA)
REFERENCES PARK (BROJ) ENABLE;

ALTER TABLE DRVO ADD CONSTRAINT DRVO_PARK_FK FOREIGN KEY (BR_PARKA)
REFERENCES PARK (BROJ) ENABLE;

ALTER TABLE DRVO ADD CONSTRAINT DRVO_ZASTICENI_OBJ_FK FOREIGN KEY (ZASTICENI_OBJ_ID)
REFERENCES ZASTICENI_OBJ (ZASTICENI_OBJ_ID) ENABLE;

ALTER TABLE SPOMENIK ADD CONSTRAINT SPOMENIK_PARK_FK FOREIGN KEY (BR_PARKA)
REFERENCES PARK (BROJ) ENABLE;

ALTER TABLE SPOMENIK ADD CONSTRAINT SPOMENIK_ZASTICENI_OBJ_FK FOREIGN KEY (ZASTICENI_OBJ_ID)
REFERENCES ZASTICENI_OBJ (ZASTICENI_OBJ_ID) ENABLE;

ALTER TABLE SPOMENIK MODIFY (ZASTICENI_OBJ_ID NOT NULL ENABLE);

ALTER TABLE SKULPTURA ADD CONSTRAINT SKULPTURA_PARK_FK FOREIGN KEY (BR_PARKA)
REFERENCES PARK (BROJ) ENABLE;

ALTER TABLE SKULPTURA MODIFY (ZASTICENI_OBJ_ID NOT NULL ENABLE);

ALTER TABLE SKULPTURA ADD CONSTRAINT SKULPTURA_ZASTICENI_OBJ_FK FOREIGN KEY (ZASTICENI_OBJ_ID)
REFERENCES ZASTICENI_OBJ (ZASTICENI_OBJ_ID) ENABLE;

ALTER TABLE FONTANA ADD CONSTRAINT FONTANA_PARK_FK FOREIGN KEY (BR_PARKA)
REFERENCES PARK (BROJ) ENABLE;

ALTER TABLE KLUPA ADD CONSTRAINT KLUPA_PARK_FK FOREIGN KEY (BR_PARKA)
REFERENCES PARK (BROJ) ENABLE;

ALTER TABLE SVETILJKA ADD CONSTRAINT SVETILKA_PARK_FK FOREIGN KEY (BR_PARKA)
REFERENCES PARK (BROJ) ENABLE;

ALTER TABLE IGRALISTE ADD CONSTRAINT IGRALISTE_PARK_FK FOREIGN KEY (BR_PARKA)
REFERENCES PARK (BROJ) ENABLE;

CREATE OR REPLACE TRIGGER TRAVNJAK_AUTO_PK
    BEFORE INSERT ON TRAVNJAK
    FOR EACH ROW
BEGIN
    SELECT ZELENA_POVRSINA_PK_SEQUENCE.NEXTVAL INTO :NEW.BROJ FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER DRVORED_AUTO_PK
    BEFORE INSERT ON DRVORED
    FOR EACH ROW
BEGIN
    SELECT ZELENA_POVRSINA_PK_SEQUENCE.NEXTVAL INTO :NEW.BROJ FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER PARK_AUTO_PK
    BEFORE INSERT ON PARK
    FOR EACH ROW
BEGIN
    SELECT ZELENA_POVRSINA_PK_SEQUENCE.NEXTVAL INTO :NEW.BROJ FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER DRVO_AUTO_PK
    BEFORE INSERT ON DRVO
    FOR EACH ROW
BEGIN
    SELECT OBJEKAT_PK_SEQUENCE.NEXTVAL INTO :NEW.BR_OBJ FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER SPOMENIK_AUTO_PK
    BEFORE INSERT ON SPOMENIK
    FOR EACH ROW
BEGIN
    SELECT OBJEKAT_PK_SEQUENCE.NEXTVAL INTO :NEW.BR_OBJ FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER SKULPTURA_AUTO_PK
    BEFORE INSERT ON SKULPTURA
    FOR EACH ROW
BEGIN
    SELECT OBJEKAT_PK_SEQUENCE.NEXTVAL INTO :NEW.BR_OBJ FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER KLUPA_AUTO_PK
    BEFORE INSERT ON KLUPA
    FOR EACH ROW
BEGIN
    SELECT OBJEKAT_PK_SEQUENCE.NEXTVAL INTO :NEW.BR_OBJ FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER FONTANA_AUTO_PK
    BEFORE INSERT ON FONTANA
    FOR EACH ROW
BEGIN
    SELECT OBJEKAT_PK_SEQUENCE.NEXTVAL INTO :NEW.BR_OBJ FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER SVETILJKA_AUTO_PK
    BEFORE INSERT ON SVETILJKA
    FOR EACH ROW
BEGIN
    SELECT OBJEKAT_PK_SEQUENCE.NEXTVAL INTO :NEW.BR_OBJ FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER IGRALISTE_AUTO_PK
    BEFORE INSERT ON IGRALISTE
    FOR EACH ROW
BEGIN
    SELECT OBJEKAT_PK_SEQUENCE.NEXTVAL INTO :NEW.BR_OBJ FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER ZASTICENI_OBJ_AUTO_PK
    BEFORE INSERT ON ZASTICENI_OBJ
    FOR EACH ROW
BEGIN
    SELECT ZASTICENI_OBJ_PK_SEQUENCE.NEXTVAL INTO :NEW.ZASTICENI_OBJ_ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER RADNIK_AUTO_PK
    BEFORE INSERT ON RADNIK
    FOR EACH ROW
BEGIN
    SELECT RADNIK_PK_SEQUENCE.NEXTVAL INTO :NEW.BR_RAD_KNJIZICE FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER RADNIK_UPDATE_BR_PARKA
    AFTER INSERT OR UPDATE OF ID_SEFA ON PARK
    FOR EACH ROW
BEGIN
    UPDATE RADNIK SET BR_PARKA = :NEW.BROJ WHERE RADNIK.BR_RAD_KNJIZICE = :NEW.ID_SEFA;
END;

